create table if not exists public.vittoria_store (
  id bigint generated by default as identity primary key,
  store_id integer references public.store_management (id),
  order_id bigint references public.orders (id),
  order_item_id bigint references public.order_items (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  price numeric,
  quantity integer check (quantity is null or quantity > 0),
  name text
);

alter table public.vittoria_store
  alter column order_id drop not null,
  alter column order_item_id drop not null,
  add column if not exists currency text,
  add column if not exists available_bool boolean default true,
  add column if not exists img_reference text,
  add column if not exists product_url text,
  add column if not exists product_id bigint,
  add column if not exists variant_id bigint,
  add column if not exists sku bigint,
  add column if not exists product_item_info text;

create index if not exists vittoria_store_store_id_idx
  on public.vittoria_store (store_id);

create index if not exists vittoria_store_order_id_idx
  on public.vittoria_store (order_id);

create index if not exists vittoria_store_order_item_id_idx
  on public.vittoria_store (order_item_id);